version: '3'
name: 3f-vision

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: M0_redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  
  image_receiver:
    image: orin_nano_messenger:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M0_image_receiver
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/run_receiver.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M0/:/usr/src/deploy/
    
  telemeter:
    image: orin_nano_messenger:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M0_telemeter
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/run_sender.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M0/:/usr/src/deploy/
      - /var/run/docker.sock:/var/run/docker.sock

  remote_control:
    image: orin_nano_messenger:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M0_remote_control
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/run_remote_control.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M0/:/usr/src/deploy/
      - /var/run/docker.sock:/var/run/docker.sock
    
  quality:
    image: orin_nano_yolov5:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M1_quality
    restart: always
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M1_quality/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M1/:/usr/src/deploy/

  yolov5:
    image: orin_nano_yolov5:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M2_detect
    restart: always
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M2_detect/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M2/:/usr/src/deploy/
    
  analyzer:
    image: orin_nano_yolov5:20240617
    runtime: nvidia
    network_mode: "host"
    container_name: M3_analyze
    restart: always
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M3_analyze/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M3/:/usr/src/deploy/