version: '3'
name: 3f-vision

services:
  # M0-redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: M0_redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  # M0-遥测数据发送
  telemeter:
    image: orin_nano_messenger:20240827
    runtime: nvidia
    network_mode: "host"
    container_name: M0_telemeter
    restart: always
    privileged: true
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/M0/run_sender.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE/:/usr/src/deploy/
      - /run/docker.sock:/run/docker.sock
      - /run/jtop.sock:/run/jtop.sock
  # M0-指令与星上时接收
  remote_control:
    image: orin_nano_messenger:20240827
    runtime: nvidia
    network_mode: "host"
    container_name: M0_remote_control
    restart: always
    privileged: true
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/M0/run_remote_control.sh
    environment:
      - DEV_WORKSPACE=$DEV_WORKSPACE
      - DEVOPS_WORKSPACE=$DEVOPS_WORKSPACE 
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE/:/usr/src/deploy/
      - $DEV_WORKSPACE/data/:/usr/src/data/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  # M0-图片接收与解析    
  image_receiver:
    image: orin_nano_messenger:20240827
    runtime: nvidia
    network_mode: "host"
    container_name: M0_image_receiver
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/M0/run_receiver.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE:/usr/src/deploy/
  # M1-图片质量评估与筛选
  quality:
    image: orin_nano_yolov5:20240912
    runtime: nvidia
    network_mode: "host"
    container_name: M1_quality
    restart: always
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M1_quality/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M1/:/usr/src/deploy/
  # M2-部件识别
  yolov5:
    image: orin_nano_yolov5:20240912
    runtime: nvidia
    network_mode: "host"
    container_name: M2_detect
    restart: always
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M2_detect/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M2/:/usr/src/deploy/
  # M3-图片择优与存储
  analyzer:
    image: orin_nano_yolov5:20240912
    runtime: nvidia
    network_mode: "host"
    container_name: M3_analyze
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/run.sh
    volumes:
      - $DEV_WORKSPACE/M3_analyze/:/usr/src/app/
      - $DEVOPS_WORKSPACE/M3/:/usr/src/deploy/
      - $DEV_WORKSPACE/data/:/usr/src/data/
  # M0-文件下载
  file_download:
    image: orin_nano_messenger:20240827
    runtime: nvidia
    network_mode: "host"
    container_name: file_download
    depends_on:
      redis:
        condition: service_healthy
    command: /usr/src/deploy/M0/run_download.sh
    volumes:
      - $DEV_WORKSPACE/M0_schedular/communication/:/usr/src/app/
      - $DEVOPS_WORKSPACE:/usr/src/deploy/
      - $DEV_WORKSPACE/data/:/usr/src/data/
